apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: webapps  # Specify the namespace if needed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest  # Use the Nginx image
          ports:
            - containerPort: 80  # Expose port 80 for HTTP
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: webapps  # Specify the namespace if needed
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer  # Expose it as a LoadBalancer if you want external access
